### ISSUE TITLE
Binding page up / page down keys?

### ISSUE THREAD

**Issue by jarreboum** [sylecn/ff-nextpage#32]
I'd like to use page down to nextpage-maybe, but I have the most difficult time finding the correct emacs key name, if it is even supported in this extension?

Also, is it possible to add previouspage and previouspage-maybe functions? Often a google search ends up in the middle of a thread and being able to browse the previous pages would be most useful.

**Comment by sylecn** [comment]
Thanks for the feedback.

To bind page down to nextpage-maybe function:
(bind "<next>" 'nextpage-maybe)
;; Page Up is <prior>, Page Down is <next> in emacs key notation.

There is no previous page feature. I will leave it as a feature request.

**Comment by jarreboum** [comment]
Thanks!
