### ISSUE TITLE
history-back issues

### ISSUE THREAD

**Issue by WINTEX** [sylecn/ff-nextpage#36]
History-back(p) not always working properly. If you're using (n) or (SPC) for next page, everything fine, but if you click on next page personally, than (p) sometimes not working. So on most non supported language sites, its has issues. And, in my opinion, it should work always, like (Backspace) or Alt+← now.
I had https://chrome.google.com/webstore/detail/backspace-to-go-back/nlffgllnjjkheddehpolbanogdeaogbc this extension before this app and its working properly, maybe you can find some hints in it?

**Comment by sylecn** [comment]
The extension that you linked use the same code as my extension for "go back" action. Both is

    window.history.back();

You need to provide the website url and the action used to trigger the problem.

**Comment by sylecn** [comment]
close because of inactivity.
