### ISSUE TITLE
user configuration

### ISSUE THREAD

**Issue by ss830716** [sylecn/ff-nextpage#37]
(bind "s" 'nextpage-maybe)
(bind "a" 'nextpage)
(bind "d" 'history-back)

user config saved
------------------------------------------------------
I use user configuration
Only the system configuration takes effect，Nothing else came into effect.
What is the reason?

**Comment by ss830716** [comment]
(bind "<next>" 'nextpage-maybe)
(bind "<right>" 'nextpage)
(bind "<left>" 'history-back)

**Comment by ss830716** [comment]
(bind ""<next>"" 'nextpage-maybe)
(bind ""<right>"" 'nextpage)
(bind ""<left>"" 'history-back)

**Comment by sylecn** [comment]
You may add
```
(enable-debug)
(enable-debug-for-key-events)
```
in user config, refresh target web page, then check for errors in browser console (Ctrl-Shift-I > Console).

If there is an error, please tell me the OS, browser version, nextpage extension version, target web page url, I will look into it.

**Comment by sylecn** [comment]
close because of inactivity.
