### ISSUE TITLE
nextpage-maybe not activating sometimes

### ISSUE THREAD

**Issue by Smylers** [sylecn/ff-nextpage#40]
The URL of a problematic page:

https://www.nntp.perl.org/group/perl.perl5.porters/2019/06/msg255289.html
https://www.google.co.uk/search?q=Firefox+extension+nextpage

Describe what's wrong on that page:

Pressing Space at the bottom of the page doesn't trigger going to the next page. Pressing N goes to the next page, as expected, so the problem doesn't seem to be with working out what the next page is, but with establishing that I am actually at the bottom of the page.

In the case of the mailing list archive, that link is to the 5th post in the thread. Using Space works perfectly for navigating from the 1st post in the thread to the 2nd, then on to the 3rd, 4th, and 5th; it's only having reached the 5th message that it suddenly declines to proceed farther. And if you press N to go to the 6th message, Space then happy navigates on to the 7th.

Tell me your browser version, OS version and nextpage addon version:

Firefox: 68
OS: Ubuntu Linux
nextpage: 2.8.4

**Comment by sylecn** [comment]
I can't reproduce the problem in firefox 68 in linux.

Maybe there is conflict with another extension? Can you reproduce this problem in a clean firefox profile?
Do you use a special desktop environment or window manager?

**Comment by Smylers** [comment]
Thanks for looking. Still happening for me on Firefox 69β. I'll try later with a clean profile.

**Comment by sylecn** [comment]
Closing because I can't reproduce it and lack of activity.
If the problem persists, please create a new issue.
