### ISSUE TITLE
"C-" bindings being ignored

### ISSUE THREAD

**Issue by Smylers** [sylecn/ff-nextpage#41]
Bindings using the `Ctrl` key don't seem to work: after defining them (then saving, and reloading the page), pressing them simply does nothing.

I thought I'd like `Ctrl`+`Space` for unconditionally going to the next page, but couldn't get it to work (I tried both with and without pointy brackets). I then discovered that nor I could I get any other `"C-"` binding to work:

    (bind "C-SPC" 'nextpage)
    (bind "<C-SPC>" 'nextpage)
    (bind "C-y" 'nextpage)
    (bind "C-." 'nextpage)

All of the above behave just the same as if I hadn't set them. `nextpage` works fine with the default `N` key, or if bound to an unmodified key, such as `.`.

Tell me your browser version, OS version and nextpage addon version:

Firefox: 68
OS: Ubuntu Linux
nextpage: 2.8.4

**Comment by sylecn** [comment]
fixed in v2.8.7
