### ISSUE TITLE
Trying to assign backspace key to go back a page

### ISSUE THREAD

**Issue by Bashymerlin** [sylecn/ff-nextpage#42]
HI, i cannot for the life of me figure out the correct abbreviation to add to assign the backspace key as the back 1 page button, its the only reason for needing this extension so i am hoping it i possible please?

I have tried

(bind "bksp" 'history-back)
(bind "BS" 'history-back)
(bind "backspace" 'history-back)
(bind "bkspc" 'history-back)

Any advice would be much appreciated

Regards

Martin

**Comment by sylecn** [comment]
The syntax you are looking for is
```
(bind "<backspace>" 'history-back)
```

Here is document from nextpage help page in case you missed it:

> If you have emacs installed, to known a key's key name (the string representation), start emacs and type C-h c, then type your key. The key name will be shown in minibuffer.
