### ISSUE TITLE
Not a bug. Just wanted to say thanks.

### ISSUE THREAD

**Issue by ernstki** [sylecn/ff-nextpage#43]
Thanks, Yuanle.

I bookmarked your extension's page on addons.mozilla.org back in 2011. But, for some reason I ended up using SpaceNext, which is now defunct. Then, after Firefox Quantum slowly killed off old extensions, I found some alternative, which is now also defunct.

Thanks for sticking with it all these years. Thanks for providing—and _continuing_ to provide, through all the WebExtension trials and tribulations—the most obvious missing functionality in all of the World Wide Web… actually using `link rel="next"` for its intended purpose.

I'm going to send a little donation using the information on your web site that I hope you can use to get a tea, coffee, or even a beer that you like.

Cheers. `:)`

**Comment by sylecn** [comment]
Oh, thanks ernstki.
