### ISSUE TITLE
可否纯JavaScript在油猴子运行呀

### ISSUE THREAD

**Issue by lyscop** [sylecn/ff-nextpage#44]
推荐来的，扩展非常强大

安装的扩展少，基本都是脚本，可以迁移纯JavaScript在油猴子运行呢

**Comment by sylecn** [comment]
这需要看 greasemonkey 是否能提供对应的API。
尤其是快捷键绑定和用户配置保存/加载。
跳转下一页的基本功能是可以迁移的。

**Comment by lyscop** [comment]
> 这需要看 greasemonkey 是否能提供对应的API。
> 尤其是快捷键绑定和用户配置保存/加载。
> 跳转下一页的基本功能是可以迁移的。

是tampermonkey上，快捷键可以，配置保存也可以，有下一页js脚本，在直播，视频网站就没效果了

**Comment by sylecn** [comment]
好的。有空的时候我看一下。
