### ISSUE TITLE
Disable predefined hotkeys.

### ISSUE THREAD

**Issue by wooshaq** [sylecn/ff-nextpage#46]
Hello, I don't have any other way of contacting you, I'm using your extension but the only key I need is the space key and the p key is constantly in the way. Is there a way to disable any other shortcuts besides the spacebar? If so how?

**Comment by sylecn** [comment]
Yes. You may add this in user preference to remove all predefined shortcuts except for space.

`(unbind-all)`
`(bind "SPC" 'nextpage-maybe)`

For more information please click help button in user preference.
