### ISSUE TITLE
能不能增加一个 只复制网页标题 功能？ 增加PgUp PgDown Home End的功能

### ISSUE THREAD

**Issue by kethoven** [sylecn/ff-nextpage#47]
能不能增加一个 只复制网页标题 功能？
增加PgUp PgDown Home End的功能

**Comment by sylecn** [comment]
> 能不能增加一个 只复制网页标题 功能？ 

好的。下次更新时加。

> 增加PgUp PgDown Home End的功能

这几个按键都支持的。对应的配置分别是 ```<prior>, <next>, <home>, <end> ```

**Comment by sylecn** [comment]
只复制网页标题 v2.10.0 里面已支持。用法示例：

```
(bind "c" 'copy-title)
```

**Comment by peace-max** [comment]
谢谢啊

> 
> 
> > 能不能增加一个 只复制网页标题 功能？
> 
> 好的。下次更新时加。
> 
> > 增加PgUp PgDown Home End的功能
> 
> 这几个按键都支持的。对应的配置分别是 `<prior>, <next>, <home>, <end> `

谢谢啊！！

**Comment by peace-max** [comment]
> 
> 
> > 能不能增加一个 只复制网页标题 功能？
> 
> 好的。下次更新时加。
> 
> > 增加PgUp PgDown Home End的功能
> 
> 这几个按键都支持的。对应的配置分别是 `<prior>, <next>, <home>, <end> `

这几个按键应该怎么写代码啊？
试了几次都是失败了。

**Comment by sylecn** [comment]
使用bind命令绑定指定的功能，比如使用PageDown翻页，需要增加配置：

```
(bind "<next>" 'nextpage)
```

可以绑定的命令，请点击配置页面的帮助按钮查看。
