### ISSUE TITLE
增加向上、向下滚屏的功能，允许用户定义快捷键

### ISSUE THREAD

**Issue by peace-max** [sylecn/ff-nextpage#50]
能不能增加向上翻页、向下翻页的功能按键设置啊？
向下翻页的功能倒是可以用空格键代替，就是向上翻页的功能比较麻烦，键盘上的pageup离空格键太远，不方便操作。希望能够增快捷键盘按键。

**Comment by sylecn** [comment]
fixed in v2.14.0 or later

增加了 scroll-up, scroll-down 命令，可以使用bind来绑定快捷键。例如

```
; 按v键向上翻页
(bind "v" 'scroll-up)
```
