### ISSUE TITLE
Prefetch and/or Prerender Next Page to increase loading speed

### ISSUE THREAD

**Issue by glowworms** [sylecn/ff-nextpage#52]
Hi,

It would be super cool if we could put Prefetch and/or Prerender on the Next Page links. This would increase the speed of the loading of the next page.

"Link prefetching is a browser mechanism, which utilizes browser idle time to download or prefetch documents that the user might visit in the near future" - https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ

Prerender - hint to browsers that the user might need the target resource for the next navigation, and therefore the browser can likely improve the user experience by preemptively fetching and processing the resource
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/prerender

**Comment by SweetyVolty** [comment]
omg please... I even only have 8 gigs of ram on win 11 but; please do this... I don't know am I the only one feeling like this but; waiting between pages or just infy scroll stuff; the waiting almost resemblence the 56,6k Modem era....

**Comment by sylecn** [comment]
This is implemented in v2.12.0. Thanks for bringing this to my attention. Please wait for the review and auto-upgrade.

v2.12.0 add prerender/prefetch support

To my surprise, this does make a difference on some websites.
So it is enabled by default. User can disable it via (disable-prefetch) in
user preferences.

**Comment by SweetyVolty** [comment]
https://i.imgur.com/Ha6QfaJ.jpeg   


Soooo no idea if it's intended or not but even surfing facebook freecycle groups are fast now. those 6 boxes normally would be like 20 or so to starts to load
