### ISSUE TITLE
Hello, it worked like a month ago and now it doesn't

### ISSUE THREAD

**Issue by Alatana** [sylecn/ff-nextpage#53]
The URL of a problematic page:

Describe what's wrong on that page:

Tell me your browser version, OS version and nextpage addon version:

**Comment by Alatana** [comment]
Problem in every google page while I am pressing "n" it doesn't go fwd to the next page.
Firefox 94.0.1,
Mac 10.15.7
Next page 2.10.3

**Comment by sylecn** [comment]
Can't reproduce on Linux on Firefox 94, nextpage 2.10.3.
I will test it later on macOS.

**Comment by sylecn** [comment]
Can't reproduce on macOS, Firefox 94, nextpage 2.10.3.

Here are some suggestions to solve the problem:
Make sure you don't accidentally hit CapsLock key.
Please check whether nextpage conflict with other hotkey management system software or other firefox add-on.
If you are comfortable with dev tools, you may debug nextpage hotkey processing by putting the following config in nextpage user preferences, save preference and reload the page you are testing. You can see key event log in dev tools Console tab.

```
(enable-debug)
(enable-debug-for-key-events)
```
