### ISSUE TITLE
Pressing P or any shortcut built in by the addons will trigger them even while typing password 

### ISSUE THREAD

**Issue by zrovihr** [sylecn/ff-nextpage#55]
I was typing username or password and the shortcut got triggered so i cant type in anything unless I disable the addons or the shortcut

**Comment by sylecn** [comment]
Hi, could you tell me which page does the problem occur?
I can fix that once I got the URL of the page.

**Comment by sylecn** [comment]
recently fix a bug on this, if the page uses shadow DOM. please retry latest version.

**Comment by zrovihr** [comment]
https://germanoid.github.io/terminal-helper/ its still happening on this page if I press P. Probably because the page doesnt really register keyboard input. (The page cannot trigger keyboard in android)

**Comment by sylecn** [comment]
For special websites where you need to disable nextpage, please add this in user preferences:

(ignore-on "https://germanoid.github.io/terminal-helper/")

I might look into the page to see if I can fix nextpage for this kind of web page. Thanks for the report.
