### ISSUE TITLE
之前支持不错的网站突然无法使用了。

### ISSUE THREAD

**Issue by popthezid** [sylecn/ff-nextpage#56]
http://www.sccnn.com/sheyingtuku/shangwujinrong/default.html
https://www.downg.com/new/0_1.html
https://www.baidu.com

经常使用的网站一直使用正常，现在无法按空格到下一页。
新建一个firefox profile单独安装nextpage测试也无效。

Firefox109,Win10 21H1,nextpage2.10.4&2.10.3

测试了一下老的Firefox104,105,106,107,108等版本nextpage都可以正常在上方网页生效。
怀疑是MV3启用，108手动打开MV3也正常使用，但109关闭MV3启用还是不可以。

**Comment by sylecn** [comment]
感谢 bug report. 该问题已于 v2.11.1 修复。请等待扩展程序审核通过后自动更新。

问题是由于 window.scrollY 现在可能返回浮点数，在与整数比较的时候可能会出现小幅偏差。导致 nextpage-maybe 判断是否到页底时出现错误。现在判断时加了10px的容错。
