### ISSUE TITLE
快捷键 n p影响功能使用

### ISSUE THREAD

**Issue by shaobeichen** [sylecn/ff-nextpage#58]
The URL of a problematic page:
https://qwerty.kaiyi.cool/

Describe what's wrong on that page:
一个打字网站，但是如果按了p就会导致回退，我尝试配置用户按键覆盖n和p，但是设为空显示解析失败

Tell me your browser version, OS version and nextpage addon version:

**Comment by sylecn** [comment]
Thanks for the bug report. Bug is confirmed in MS edge browser.

As a work around, please disable nextpage on this website, add in user preferences:

(ignore-on "https://qwerty.kaiyi.cool/")

**Comment by caliban511** [comment]
内置快捷键不能取消真的很烦人，而且现在foxfire里翻下一页的功能也废了，看看up什么时候有时间修一下吧。
