### ISSUE TITLE
Wordpress issue

### ISSUE THREAD

**Issue by SpitFire-666** [sylecn/ff-nextpage#59]
The URL of a problematic page:
https://socket3.wordpress.com/blog/page/4/

Describe what's wrong on that page:
Pressing SPACE at the bottom of the page goes to a specific article instead of page 5
https://socket3.wordpress.com/2020/11/21/2020-the-year-that-went-down-like-a-disk-full-of-bad-sectors/#more-7967

Tell me your browser version, OS version and nextpage addon version:
FF115, Win10, 2.16.1

Thanks!

**Comment by sylecn** [comment]
fixed in nextpage v2.16.2 or later.
