### ISSUE TITLE
Nextpage in www.google.com/search

### ISSUE THREAD

**Issue by hopalongrock** [sylecn/ff-nextpage#60]
The URL of a problematic page:
www.google.com/search

Describe what's wrong on that page:

It would be great if the NextPage addon would also work for "More results' in Google search.

Tell me your browser version, OS version and nextpage addon version:
Firefox 119.0.1, Windows 10 22H2  Nextpage 2.16.1

**Comment by sylecn** [comment]
fixed in v2.16.3 or later.

**Comment by hopalongrock** [comment]
Thank you, works fine!
